### ISSUE TITLE
Count duplicates and delete them when icon is clicked

### ISSUE THREAD

**Issue by allanwind** [igorlogius/close-duplicate-tabs#1]
**Is your feature request related to a problem? Please describe.**

I like the minimal nature of the add-on but the "show remove notification" isn't optimal either set or unset.  If set you get interrupted with a pop-up that you have to dismiss.  If unset you have pay close attention notice that one of your tabs was just closed. Both demand your attention now but the only cost of delaying action is extra memory usage.

**Describe the solution you'd like**

Would it be possible for the add-on to simply count number of duplicates, show if >0 (instead of on), and when you click the icon it would delete the duplicate the duplicates like now?

**Describe alternatives you've considered**

Duplicate Tab Close works similar but I suspect is has a bug that cause all UI dialogs to be auto-closed right away.  In either case, it is kinda bloated, and you have to click on the icon, wait for it show the tabs, and only then can you close it.  FoxyTab, TabSearch, Tab Deduber all lack the visual indication of duplicate tabs.

**Additional context**

**Comment by igorlogius** [comment]
@allanwind 

https://addons.mozilla.org/en-US/firefox/addon/close-duplicate-tabs/

Hope this is what you wanted.

**Comment by allanwind** [comment]
Not sure why my email rely didn't make it here...

Thanks so much for the quick change, Andy, and I apologize for                                                         
missing your email earlier.                                                                                            
                                                                                                                       
Click to delete works perfectly!                                                                                       
                                                                                                                       
The only change I would really like to see is a badge (I think                                                         
it's called; decoration on top of the icon) with duplicate count                                                       
iff count > 0.  That way you can glance at the icon and see if you                                                     
need to click it.                                                                                                      
                                                                                                                       
My preference would be to eliminate the dialog window entirely "No                                                     
tabs closed.", "Number of tabs: x" as it doesn't tell me anything                                                      
useful.  If you want to keep it around, I suggest you lower the                                                        
timeout form 15s to ~3s:                                                                                               
                                                                                                                       
https://ux.stackexchange.com/questions/11203/how-long-should-a-temporary-notification-toast-appear

**Comment by allanwind** [comment]
Sorry, this is pretty embarrassing but I might have been mixed up different add-ons that are very similarly named.  I tried all of them before asking for your help.  Looking at "Close Duplicate Tabs" it works.  For me it takes 2-3 seconds for the plugin to notice duplicates (among 76 tabs) which seems kinda sluggish, when I switch a tab, it resets the count to an older value and then seem to restart a scan which again takes 2-3.  Any way to speed that up to 0.2s so it feels instant and/or caching the data so it doesn't change when switching tabs?   When clicking on to delete duplicates it again waits 2-3 seconds to update.  It would be better if you reset it to 0 immediately so you know it registered the click.

**Comment by allanwind** [comment]
And found a bug... If I open my subscription page on youtube and open a video twice in a background (middle click) the current icon doesn't notice the update, but if then go to one of the duplicate pages it does see them.  It's seem to be counting number of duplicates of the current tab.  It might have a use but I prefer just getting a single duplicate count across all tabs.

**Comment by igorlogius** [comment]
> Sorry, this is pretty embarrassing but I might

No, i made this addon and moved your issue here.  No fault on your side. 


1. that is intended ... the duplicate calculation is delayed until the users settels on a tab, but i can add an option to reduce the delay 
2. i wanted to make sure that the calculation is not done to frequently ... so even people with a lot of open tabs can still use this addon. If i wanted more accurate values ... i need to 1) do more monitoring (on create, closed, tab moved ... etc.) and querying and comparing each time is gone cost addional resources. So i settled to only re-calculate the dups number, when a tab is switched or the toolbar button has been  clicked. 
3. done

> It seems to counting number of duplicates of the current tab.

Well, that was how i read your request ... 

>  but I would just like a single count of duplicates across all tabs.

Then i would expect the action to also Close ALL Duplicates ... is that what you want? 

> ... want to leave the oldest tab in each group of duplicates.

Tabs dont exactly have an age ... and while i could add tracking to calculate this value ... i rather not and simply use the built-in attributes which currenlty only leaves last-access time.

**Comment by allanwind** [comment]
>     1. that is intended ... the duplicate calculation is delayed until the users settels on a tab, but i can add an option to reduce the delay , for people who think their PC can handle it
> 
>     2. i wanted to make sure that the calculation is not done to frequently ... so even people with a lot of open tabs can still use this addon. If i wanted more accurate values ... i need to 1) do more monitoring (on create, closed, tab moved ... etc.) and querying and comparing each time is gone cost addional resources. So i settled to only re-calculate the dups number, when a tab is switched or the toolbar button has been  clicked.

That makes sense when you do 1 scan per tab (O(n^2) but if you only do 1 across all tabs I O(n) when a tab is open/closed I think that would make it a non-issue, no?

> > It seems to counting number of duplicates of the current tab.
> 
> Well, that was how i read your request ...
> 
> > but I would just like a single count of duplicates across all tabs.
> 
> Then i would expect the action to also Close ALL Duplicates ... is that what you want?

Yes!

> Tabs dont exactly have an age ... and while i could add tracking to calculate this value ... i rather not and simply use the built-in attributes which currenlty only leaves last-access time.

Hmm... it looks like https://github.com/andymckay/tab-closer/blob/master/background.js does it via via iteration order (to the last opened tab is closed).

**Comment by allanwind** [comment]
No, that add-on doesn't have the badge count which is essential.

**Comment by igorlogius** [comment]
Btw. Your O-notation calculation is wrong ..

while i can gather the tab information in O(n) in one sweep ... in the worst case i still need to compare each tab against every other tab. => O(n*n)  

This can be optimized by exempting already identified duplicates after each comparison... but that doenst change the Worst Case in which every tab is unique.

**Comment by allanwind** [comment]
You know way more about this than m so it's quite possible.  Agree with your reasoning when you need a count of duplicates per tab, but I was thinking if you only need 1 count across all tabs you can it in O(n) time if you store the key in a hash table no?
