### ISSUE TITLE
Option to automatically close duplicated tabs without having to click

### ISSUE THREAD

**Issue by federico2407** [igorlogius/close-duplicate-tabs#6]
I would like the option to automatically close duplicated tabs without having to click on the extension icon so i can hide it in the extension tray

**Comment by federico2407** [comment]
> That option already exists.
> 
> ![image](https://private-user-images.githubusercontent.com/67047467/298287717-4936ee61-1430-48e7-bbc5-b108399ad7a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDk2MjQsIm5iZiI6MTcwNTg0OTMyNCwicGF0aCI6Ii82NzA0NzQ2Ny8yOTgyODc3MTctNDkzNmVlNjEtMTQzMC00OGU3LWJiYzUtYjEwODM5OWFkN2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDE1MDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYzY3MTg3MGU0NDFiNTA5MzJlZTgyMDI1ZjIzMjQzZTM2YzcyMjJiMTY4YTBlZDRkMjdkN2Y2OTQyYjI4N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y5nWTP_FQmr4amZLIKtr-ZNeIR7d3jKEgN_OzTCazrc)
> 
> You can set a custom shortcut/hotkey for the action, like this.
> demo-2024-01-20_15.30.32.mp4
> 
> Does this help, or did you mean something else?

I meant i wanted to hide the extension and forget it existed while it deletes duplicated tabs with no user input

**Comment by igorlogius** [comment]
> deletes duplicated tabs with no user input

That feature is not in scope for this addon, but you might want to take a look at these: 

- https://addons.mozilla.org/en-US/firefox/addon/duplicate-tabs-closer/
- https://addons.mozilla.org/en-US/firefox/addon/smart-prevent-duplicate-tabs/
- https://addons.mozilla.org/en-US/firefox/addon/dont-open-duplicate-tabs/
- https://addons.mozilla.org/en-US/firefox/addon/tab-deduper/

Hope this info helps.

**Comment by igorlogius** [comment]
> deletes duplicated tabs with no user input

That feature is not in scope for this addon, but you might want to take a look at these: 

- https://addons.mozilla.org/en-US/firefox/addon/duplicate-tabs-closer/
- https://addons.mozilla.org/en-US/firefox/addon/smart-prevent-duplicate-tabs/
- https://addons.mozilla.org/en-US/firefox/addon/dont-open-duplicate-tabs/
- https://addons.mozilla.org/en-US/firefox/addon/tab-deduper/

Hope this info helps.
