### ISSUE TITLE
Add an exclude list of URL or not care about new tab.

### ISSUE THREAD

**Issue by cortx-fr** [igorlogius/close-duplicate-tabs#7]
**Is your feature request related to a problem? Please describe.**
I want to add some tab as delimiter to separate list of tabs and for that I use the "home" button on firefox that open a new empty tab without any URL and named "New tab" in english or "Nouvel 

**Describe the solution you'd like**
I want to have a list of excluded tab list that containt some url to exclude to be closed or exclude tab that have not URL.

Here is an example of how I manage many tabs opend from different website. 
![image](https://github.com/igorlogius/close-duplicate-tabs/assets/63169493/08cf27d4-4f34-4a31-9a50-cb095675d94f)

Thank you for considering my request.

**Comment by igorlogius** [comment]
`1.0.17` adds a shortcut to ignore selected tabs and a second one to clear the ignored.

![Screenshot_2024-03-11_22-06-06](https://github.com/igorlogius/close-duplicate-tabs/assets/67047467/3684d83d-8500-4900-b81c-ae2b23306b14)

All ignored tabs wont be counted on the toolbar badge or closed when clicking the toobar button.

**Comment by igorlogius** [comment]
Please check and let me know if the fix/solution meets your requirments, if not, feel free to comeback and let me know what you think isn't right or doenst work.

**Comment by cortx-fr** [comment]
Hello
Didn't received the notification about answer in this topic. 
The solution meets the requirement but only work for the selected one. 
In my exemple of using new tab as separator, If I have 4 separator and I only use your fix on one tab, only this tab is protected, not the 3 others so I've to select each tab individualy.
Is it possible to add to the ignore list all the tabs that trigger the multiple tab of the one I'm ignoring ?

If I've 4 tab on website.com, all of those tab are ignored if I press F4 on one of those.

**Comment by igorlogius** [comment]
You can have multiple tabs selected (aka. highlighted) and when multiple tabs are selected, the shortcut will ignore all selected tabs. 

You can do the selection manually via CTRL and/or SHIFT or use an addon that allows you to quickly select tabs which meet your criterias (like tabs with the same domain).
With this for example: https://addons.mozilla.org/en-US/firefox/addon/select-tabs

**Comment by cortx-fr** [comment]
Thank you for those advices

**Comment by igorlogius** [comment]
Sidenote: adding new tabs, does not invalidate any previous ignored, so you do not need to select and ignore everything in one go, but can make multiple selections and ignore them one after another.
