### ISSUE TITLE
[Feature Request] Display or copy a list of the tabs found to be duplicates (for inspection before closing)

### ISSUE THREAD

**Issue by shodanx2** [igorlogius/close-duplicate-tabs#8]
Hi,

Sometimes I wonder what it is closing.
I would like to verify it is really only closing duplicates.
I have a feeling, some of the tabs are not actually duplicates.

I suggest, a right click context menu option. 
To copy to clipboard a list of all tabs deemed duplicates.

To help you accomplish this, I would like to direct you to this addon which also copies many tabs to clipboard

https://github.com/igorlogius/copy-tabs

This addon copies selected tabs to clipboard. I am hoping you can re-use some of the code to copy the duplicate tabs to clipboard.

**Comment by igorlogius** [comment]
> Sometimes I wonder what it is closing.

The feature of a UI that shows the duplicates was earlier on dismissed and is still out of scope, but there is another addon on AMO, which AFAIK, has this feature.

> I have a feeling, some of the tabs are not actually duplicates.

Well, per definition every tab that shares the same cookiestore (aka. container) and has the same URL as another tab is a duplicate ... That doesnt mean that the tabs display the same content.

> I suggest, a right click context menu option.
> To copy to clipboard a list of all tabs deemed duplicates.

Aside from my previous statement, i really dont know what information could be copied into the clipboard that would help, aside maybe from a screenshot.


> To help you accomplish this, I would like to direct you to this addon which also copies many tabs to clipboard
> https://github.com/igorlogius/copy-tabs

I assume you are intentionally refering me to my own addon, to stroke my ego. ;)

**Comment by shodanx2** [comment]
Oh, Hi Igorlogius ! 
I did not realize you also made close-duplicate-tabs !
"copy-tabs" is just the first thing that came to mind when it came to copying tabs urls to clipboard, I use that one all the time.
I miss "Open Tabs from clipboard URLs"

Back to the subject matter. 

Earlier it was saying I had nearly 250 duplicate tabs out of about 1500 and I thought that was very high. 
I was curious to know which tabs were these duplicate tabs before closing them !
I am still learning to trust close-duplicate-tabs

I guess I just do have lots of duplicate tabs !

---

BTW, we did talk earlier when you were still on reddit.
You made an addon for me, to obtain a particular piece of information from multiple tabs at once, and copy it all to clipboard (for then using in a spreadsheet)  I have unfortunately lost this addon in a OS reinstall. Do you still have this addon by any chance ? It was very useful cutting through the noise on Ali X !

**Comment by igorlogius** [comment]
> I did not realize you also made close-duplicate-tabs !

All good, i do have too many addons ... including the retired ones in my not-on-amo repo 

> I am still learning to trust close-duplicate-tabs

never trust anyone :-) 


> I miss "Open Tabs from clipboard URLs"

that should still be on the not-on-amo repo, i think i took it down because there was already an established one on AMO with basically the same function

> You made an addon for me, to obtain a particular piece of information from multiple tabs at once, and copy it all to clipboard

i think just rebuild that addon and made it a bit nicer
https://addons.mozilla.org/en-US/firefox/addon/gather-from-tabs/
 but if you prefer the old one, it should still be in the not-on-amo repo.
